# Create a pull request to update the bazel central registry
# when a new release has been cut.
name: BCR

on:
  release:
    types: [published]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Checkout the released version of this repo
        uses: actions/checkout@v2
        with:
          ref: ${{ GITHUB_REF }}
          path: ${{ GITHUB_ACTION_REPOSITORY }}
      - name: Checkout bcr
        uses: actions/checkout@v3
        with:
          #TODO: change to bazelbuild
          repository: kormide/bazel-central-registry
          path: bcr
      - run: |
          cd bcr
          git checkout -b "$GITHUB_ACTION_REPOSITORY@${{ steps.get_version.outputs.VERSION }}"
      - name: Create the bcr entry
        run: node create-bcr-entry.js $GITHUB_ACTION_REPOSITORY bcr
